export const APP_CONFIG = {
  NAME: 'AI Sales Assistant',
  VERSION: '1.0.0',
  DESCRIPTION: 'Autonomous Agentic Commerce Platform with Explainable AI & Razorpay Integration',
  API_PREFIX: '/api/v1',
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PROFIT_MARGIN_PERCENT: 25,
  MAX_DISCOUNT_PERCENT: 30,
  DEFAULT_CURRENCY: 'INR',
  RATE_LIMIT: {
    WINDOW_MS: 60 * 1000, // 1 minute
    MAX_REQUESTS: 100,
    CHAT_MAX_REQUESTS: 20,
  },
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
