import type { AssistantProduct, DynamicBundle } from '@ai-sales-assistant/types';

export const ASSISTANT_CATALOG: AssistantProduct[] = [
  {
    id: 'nx-ear-001',
    name: 'Nexus Pro Wireless Earbuds',
    sku: 'NX-EAR-001',
    brand: 'Nexus',
    category: 'Audio',
    description: 'Flagship true wireless earbuds with Hybrid Active Noise Cancellation (42dB), 30-hour battery life, and spatial audio.',
    longDescription:
      'Engineered for audiophiles and commuters, the Nexus Pro delivers studio-grade sound reproduction with customized 11mm titanium dynamic drivers. Features 42dB Hybrid ANC, 6-mic beamforming ENC for crystal-clear calls, IPX5 water resistance, and Qi wireless fast charging.',
    price: 12490,
    comparePrice: 14999,
    costPrice: 7800,
    margin: 0.375,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['wireless', 'earbuds', 'noise-cancellation', 'anc', 'audio', 'bluetooth', 'premium', 'apple', 'flagship'],
    stock: 142,
    lowStock: 20,
    rating: 4.8,
    reviewsCount: 1248,
    deliveryEstimate: 'Free Next-Day Delivery by 2 PM',
    isFeatured: true,
    badge: 'Best Seller',
    features: [
      '42dB Hybrid Active Noise Cancellation',
      '30-Hour Total Playtime (8h earbuds + 22h case)',
      '6-Mic AI Environmental Noise Cancellation',
      'Custom 11mm Titanium Drivers with Spatial Audio',
      'IPX5 Sweat & Water Resistance',
      'Qi Wireless & USB-C Quick Charge (10 min = 2 hrs)',
    ],
    specs: [
      { name: 'Driver Size', value: '11mm Titanium Composite' },
      { name: 'Bluetooth Version', value: 'Bluetooth 5.3 + LE Audio' },
      { name: 'Battery Capacity', value: '55mAh (per bud) / 500mAh (case)' },
      { name: 'Water Resistance', value: 'IPX5 Certified' },
      { name: 'Weight', value: '4.8g per earbud' },
      { name: 'Warranty', value: '1 Year Full Replacement' },
    ],
    reviews: [
      {
        id: 'rev-1',
        author: 'Aditya S.',
        rating: 5,
        date: '3 days ago',
        comment: 'Best ANC under ₹15k! Blocks metro noise effortlessly and battery easily lasts all day.',
        verified: true,
      },
      {
        id: 'rev-2',
        author: 'Rohan V.',
        rating: 5,
        date: '1 week ago',
        comment: 'The soundstage is super crisp with punchy bass that doesn’t overpower vocals.',
        verified: true,
      },
    ],
  },
  {
    id: 'blt-ear-002',
    name: 'Bolt Sonic ANC Earbuds',
    sku: 'BLT-EAR-002',
    brand: 'Bolt',
    category: 'Audio',
    description: 'Affordable wireless earbuds featuring Active Noise Cancellation, low latency gaming mode, and 28-hour playtime under ₹3,000.',
    longDescription:
      'The Bolt Sonic sets the benchmark for budget audio. With 28dB Active Noise Cancellation, ultra-low 45ms gaming latency, 10mm graphene dynamic bass drivers, and IPX4 splash resistance, it delivers flagship value for students and young professionals.',
    price: 2499,
    comparePrice: 3999,
    costPrice: 1400,
    margin: 0.44,
    images: [
      'https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['wireless', 'earbuds', 'under-3000', 'budget', 'anc', 'gaming', 'audio', 'bolt', 'bass'],
    stock: 280,
    lowStock: 40,
    rating: 4.6,
    reviewsCount: 2840,
    deliveryEstimate: 'Free 2-Day Delivery',
    isFeatured: true,
    badge: 'Top Pick under ₹3K',
    features: [
      '28dB Active Noise Cancellation',
      '45ms Ultra-Low Latency Gaming Mode',
      '28-Hour Total Playtime with Fast Charge',
      '10mm Dynamic Graphene Bass Drivers',
      'Quad-Mic AI Call Clarity',
      'IPX4 Splash Proofing',
    ],
    specs: [
      { name: 'Driver Size', value: '10mm Dynamic Graphene' },
      { name: 'Bluetooth Version', value: 'Bluetooth 5.3' },
      { name: 'Latency', value: '45ms Gaming Sync' },
      { name: 'Battery Life', value: '7h (buds) + 21h (case)' },
      { name: 'Weight', value: '4.1g per earbud' },
      { name: 'Warranty', value: '1 Year Manufacturer Warranty' },
    ],
    reviews: [
      {
        id: 'rev-3',
        author: 'Pooja K.',
        rating: 5,
        date: '2 days ago',
        comment: 'Unbeatable value for ₹2,499. The noise cancellation works great in libraries and cafes!',
        verified: true,
      },
    ],
  },
  {
    id: 'au-wt-002',
    name: 'Aura Smart Watch Ultra',
    sku: 'AU-WT-002',
    brand: 'Aura',
    category: 'Wearables',
    description: 'Premium aerospace titanium smartwatch with 1.96" AMOLED display, dual-band GPS, comprehensive ECG, and 7-day battery.',
    longDescription:
      'Engineered for endurance athletes and executives. Features a sapphire crystal AMOLED screen (1000 nits), dual-frequency GPS, multi-sensor health suite (ECG, SpO2, Heart Rate, Stress), and Bluetooth calling with acoustic noise reduction.',
    price: 18999,
    comparePrice: 22999,
    costPrice: 11500,
    margin: 0.395,
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['smartwatch', 'wearables', 'fitness', 'gps', 'health', 'aura', 'premium', 'ecg', 'amoled'],
    stock: 86,
    lowStock: 15,
    rating: 4.9,
    reviewsCount: 892,
    deliveryEstimate: 'Free Next-Day Delivery by 2 PM',
    isFeatured: true,
    badge: 'Pro Choice',
    features: [
      '1.96" AMOLED Sapphire Display (1000 Nits Always-On)',
      'Dual-Band Multi-Satellite GPS Navigation',
      'ECG + Continuous SpO2 & Heart Rate Tracking',
      '7-Day Heavy Usage Battery (14 Days in Power Save)',
      'Aerospace Grade Titanium Bezel & 5ATM Water Resistance',
      'AI Fitness Coach with 110+ Workout Profiles',
    ],
    specs: [
      { name: 'Display', value: '1.96" AMOLED (410x502 px)' },
      { name: 'Case Material', value: 'Titanium + Ceramic Back' },
      { name: 'Sensors', value: 'ECG, PPG, SpO2, Barometer, Compass' },
      { name: 'Water Resistance', value: '5ATM + IP68' },
      { name: 'Battery Capacity', value: '460mAh (7-day life)' },
      { name: 'Connectivity', value: 'Bluetooth 5.3 + Dual GPS' },
    ],
    reviews: [
      {
        id: 'rev-4',
        author: 'Vikram K.',
        rating: 5,
        date: '5 days ago',
        comment: 'The display is breathtakingly bright even in direct sunlight. GPS locks in 3 seconds!',
        verified: true,
      },
    ],
  },
  {
    id: 'nv-fit-003',
    name: 'Nova Pro AMOLED Fitness Watch',
    sku: 'NV-FIT-003',
    brand: 'Nova',
    category: 'Wearables',
    description: 'Sleek budget fitness smartwatch with 1.43" AMOLED screen, Bluetooth calling, 120+ sports modes, and 10-day battery.',
    longDescription:
      'The Nova Pro combines lightweight comfort with high performance. Offers sharp 1.43-inch AMOLED visuals, 24/7 heart rate and sleep tracking, AI voice assistant integration, and Bluetooth calling.',
    price: 3499,
    comparePrice: 5999,
    costPrice: 1950,
    margin: 0.44,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['smartwatch', 'fitness', 'wearables', 'budget', 'amoled', 'calling', 'under-5000'],
    stock: 190,
    lowStock: 30,
    rating: 4.7,
    reviewsCount: 1640,
    deliveryEstimate: 'Free 2-Day Delivery',
    badge: 'Popular',
    features: [
      '1.43" Vivid AMOLED Curved Screen',
      'Single-Chip Bluetooth Calling with Mic & Speaker',
      '10-Day Battery Life on Single Charge',
      '120+ Sports Modes with Auto-Detection',
      'IP68 Dust and Water Resistant',
    ],
    specs: [
      { name: 'Display', value: '1.43" AMOLED HD' },
      { name: 'Battery Life', value: '10 Days Normal / 5 Days Calling' },
      { name: 'Water Resistance', value: 'IP68' },
      { name: 'Compatibility', value: 'Android 6.0+ & iOS 11.0+' },
    ],
  },
  {
    id: 'qt-sp-004',
    name: 'Quantum 360° Bluetooth Speaker',
    sku: 'QT-SP-004',
    brand: 'Quantum',
    category: 'Audio',
    description: 'Rugged waterproof portable speaker with 360° omnidirectional sound, 24W punchy bass, and 18-hour battery.',
    longDescription:
      'Immerse your space in rich acoustics. Equipped with dual passive radiators and DSP audio algorithms for deep, distortion-free bass. IPX7 waterproof rating lets you take the party from poolside to mountaintop.',
    price: 7999,
    comparePrice: 9999,
    costPrice: 4600,
    margin: 0.425,
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['speaker', 'bluetooth', 'audio', 'portable', 'waterproof', 'quantum', 'outdoor', 'bass'],
    stock: 124,
    lowStock: 25,
    rating: 4.7,
    reviewsCount: 654,
    deliveryEstimate: 'Free 2-Day Delivery',
    badge: 'Trending',
    features: [
      '360° Spatial Acoustic Audio with 24W Power',
      'IPX7 Complete Waterproof & Float Design',
      '18-Hour Continuous Playtime',
      'TWS Mode: Pair 2 Speakers for Stereo Audio',
      'Built-in Power Bank function to charge phones',
    ],
    specs: [
      { name: 'Output Power', value: '24W RMS (Dual 12W Drivers)' },
      { name: 'Battery', value: '5200mAh Li-ion' },
      { name: 'Waterproofing', value: 'IPX7 Submersible' },
      { name: 'Weight', value: '680g' },
    ],
  },
  {
    id: 'lm-dl-005',
    name: 'Lume Desk Lamp Pro with Wireless Charger',
    sku: 'LM-DL-005',
    brand: 'Lume',
    category: 'Home & Office',
    description: 'Ergonomic architectural LED desk lamp with auto-dimming ambient sensor, adjustable color temp, and 15W Qi charging base.',
    longDescription:
      'Designed to reduce eye strain during late-night coding or design sessions. Features CRI > 95 daylight color reproduction, multi-pivot aluminum arm, touch sliders for 5 color modes and 10 brightness steps, plus integrated 15W fast wireless charging pad.',
    price: 4499,
    comparePrice: 5999,
    costPrice: 2600,
    margin: 0.42,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['lamp', 'desk', 'led', 'home', 'office', 'workspace', 'lighting', 'wireless-charger', 'setup'],
    stock: 203,
    lowStock: 30,
    rating: 4.8,
    reviewsCount: 780,
    deliveryEstimate: 'Free Next-Day Delivery by 2 PM',
    badge: 'Top Setup Pick',
    features: [
      'High Color Rendering Index (CRI > 95) Eye Care Light',
      'Integrated 15W Fast Qi Wireless Charging Base',
      'Auto-Brightness Ambient Light Sensor',
      '5 Color Temperatures (2700K Warm to 6500K Cool)',
      'Full Range 3-Axis Multi-Angle Articulation',
    ],
    specs: [
      { name: 'Power Consumption', value: '18W (LED) + 15W (Qi output)' },
      { name: 'Color Temp', value: '2700K - 6500K' },
      { name: 'Material', value: 'Anodized Aviation Aluminum' },
      { name: 'Lifespan', value: '50,000 Hours LED' },
    ],
  },
  {
    id: 'sw-pb-006',
    name: 'Swift 65W GaN Power Bank 20000mAh',
    sku: 'SW-PB-006',
    brand: 'Swift',
    category: 'Accessories',
    description: 'Ultra-fast laptop-grade 65W Power Delivery power bank with digital smart display and triple-device simultaneous charging.',
    longDescription:
      'Power your MacBook, iPad, iPhone, or Android phone at maximum speed. Airline-safe 20,000mAh capacity provides 4 full smartphone charges or 1.2 full laptop charges. Features intelligent real-time wattage OLED screen.',
    price: 2999,
    comparePrice: 3999,
    costPrice: 1750,
    margin: 0.416,
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['power-bank', 'charging', 'fast-charging', 'accessories', 'usb-c', 'gan', 'under-3000', 'portable'],
    stock: 312,
    lowStock: 50,
    rating: 4.8,
    reviewsCount: 1950,
    deliveryEstimate: 'Free 2-Day Delivery',
    badge: 'Value King',
    features: [
      '65W USB-C PD 3.0 (Fast charges laptops and phones)',
      '20,000mAh Airline Flight-Safe Capacity',
      'Smart Real-Time Digital LED Power & Wattage Display',
      'Triple Port Output (2x USB-C + 1x USB-A QC 3.0)',
      'Recharges from 0 to 80% in just 75 minutes',
    ],
    specs: [
      { name: 'Capacity', value: '20,000mAh / 74Wh' },
      { name: 'Max Output', value: '65W Power Delivery' },
      { name: 'Input', value: '65W Type-C Fast In' },
      { name: 'Weight', value: '410g' },
    ],
  },
  {
    id: 'cv-wc-007',
    name: 'ClearView 4K Ultra HD AI Webcam',
    sku: 'CV-WC-007',
    brand: 'ClearView',
    category: 'Home & Office',
    description: 'Pro streaming 4K 60FPS webcam with Sony STARVIS sensor, AI auto-framing, dual noise-canceling microphones, and privacy shutter.',
    longDescription:
      'Upgrade your video conferences, podcasts, and streams with true 4K resolution. The Sony STARVIS sensor provides unmatched low-light performance while AI auto-framing keeps you centered.',
    price: 5499,
    comparePrice: 6999,
    costPrice: 3200,
    margin: 0.418,
    images: [
      'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['webcam', '4k', 'camera', 'office', 'streaming', 'zoom', 'accessories', 'home'],
    stock: 78,
    lowStock: 15,
    rating: 4.8,
    reviewsCount: 512,
    deliveryEstimate: 'Free Next-Day Delivery by 2 PM',
    badge: 'Creator Choice',
    features: [
      '4K 60FPS Ultra HD Video with Sony STARVIS Sensor',
      'AI-Powered Auto Framing & Face Tracking',
      'Dual Stereo Microphones with AI Noise Suppression',
      'Magnetic Hardware Privacy Lens Shutter',
      'Adjustable Field of View (65°, 78°, 90°)',
    ],
    specs: [
      { name: 'Resolution', value: '4K @ 30FPS / 1080p @ 60FPS' },
      { name: 'Sensor', value: '1/2.8" Sony STARVIS CMOS' },
      { name: 'Focus', value: 'Fast Phase-Detection Auto Focus' },
      { name: 'Connection', value: 'USB-C Plug & Play' },
    ],
  },
  {
    id: 'apx-kb-008',
    name: 'Apex Pro RGB Mechanical Wireless Keyboard',
    sku: 'APX-KB-008',
    brand: 'Apex',
    category: 'Gaming & Tech',
    description: 'Hot-swappable tri-mode wireless mechanical keyboard with custom pre-lubed switches, PBT keycaps, and volume knob.',
    longDescription:
      'Engineered for maximum typing comfort and gaming precision. Connect up to 5 devices across 2.4GHz wireless, Bluetooth 5.1, or USB-C. Includes sound-dampening silicone gaskets for creamy typing acoustics.',
    price: 4499,
    comparePrice: 6499,
    costPrice: 2500,
    margin: 0.444,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['keyboard', 'mechanical', 'gaming', 'wireless', 'rgb', 'tech', 'accessories', 'typing'],
    stock: 110,
    lowStock: 20,
    rating: 4.9,
    reviewsCount: 940,
    deliveryEstimate: 'Free 2-Day Delivery',
    badge: 'Staff Pick',
    features: [
      'Tri-Mode Connectivity (2.4GHz + BT 5.1 + USB-C)',
      'Pre-Lubed Gateron Yellow Switches (Hot-Swappable 5-pin)',
      'Double-Shot PBT Cherry Profile Keycaps',
      'Multi-Layer Gasket Structure for Creamy Acoustics',
      '4000mAh Battery (Up to 200 Hours without RGB)',
    ],
    specs: [
      { name: 'Layout', value: '75% Compact (82 Keys + Rotary Knob)' },
      { name: 'Switches', value: 'Hot-Swappable Linear / Tactile' },
      { name: 'Battery', value: '4000mAh Rechargeable' },
      { name: 'Backlight', value: '16.8M South-Facing Per-Key RGB' },
    ],
  },
  {
    id: 'mg-pad-009',
    name: 'MagCharge 3-in-1 Foldable Charging Stand',
    sku: 'MG-PAD-009',
    brand: 'MagCharge',
    category: 'Accessories',
    description: 'Foldable magnetic travel charging stand for iPhone, Apple Watch/Smartwatch, and AirPods simultaneously.',
    longDescription:
      'Eliminate nightstand clutter. This pocket-sized folding charger charges your phone (15W), smartwatch (5W), and earbuds (5W) with strong N52 neodymium magnets and intelligent temperature regulation.',
    price: 2199,
    comparePrice: 3499,
    costPrice: 1100,
    margin: 0.5,
    images: [
      'https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['charger', 'magsafe', 'wireless', 'accessories', 'apple', 'travel', 'stand', 'under-3000'],
    stock: 245,
    lowStock: 35,
    rating: 4.7,
    reviewsCount: 1120,
    deliveryEstimate: 'Free 2-Day Delivery',
    badge: 'Travel Essential',
    features: [
      '3-in-1 Simultaneous Fast Charging (Phone + Watch + Buds)',
      '180° Foldable Pocket Design with Soft Silicone Hinge',
      'Strong N52 Magnetic Alignment with Stand Mode',
      'Over-Charge, Temperature & Short-Circuit Safety Suite',
    ],
    specs: [
      { name: 'Output', value: '15W Max Phone + 5W Watch + 5W Buds' },
      { name: 'Dimensions', value: '85 x 85 x 24 mm (folded)' },
      { name: 'Weight', value: '185g' },
    ],
  },
  {
    id: 'erg-ms-010',
    name: 'ErgoGrip Wireless Vertical Mouse',
    sku: 'ERG-MS-010',
    brand: 'ErgoGrip',
    category: 'Accessories',
    description: 'Scientific ergonomic vertical mouse designed to alleviate wrist strain and carpal tunnel fatigue.',
    longDescription:
      'Engineered by biomechanical specialists. The 57° handshake angle places your forearm in a neutral posture. Features silent clicks, precision 4000 DPI optical sensor, and rechargeable battery.',
    price: 1799,
    comparePrice: 2499,
    costPrice: 900,
    margin: 0.5,
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['mouse', 'ergonomic', 'accessories', 'wireless', 'office', 'under-2000', 'under-3000'],
    stock: 180,
    lowStock: 25,
    rating: 4.6,
    reviewsCount: 620,
    deliveryEstimate: 'Free 2-Day Delivery',
    badge: 'Ergonomic Choice',
    features: [
      '57° Handshake Angle reduces wrist strain by 70%',
      'Ultra-Silent Omron switches (90% quieter click)',
      'Adjustable 800 - 4000 DPI Precision Sensor',
      'Dual Connection: Bluetooth + 2.4GHz Nano Receiver',
    ],
    specs: [
      { name: 'DPI Levels', value: '800 / 1200 / 2400 / 4000' },
      { name: 'Battery', value: 'Rechargeable 600mAh (60-day life)' },
      { name: 'Weight', value: '120g' },
    ],
  },
];

export const PRECONFIGURED_BUNDLES: DynamicBundle[] = [
  {
    id: 'bundle-home-office',
    name: 'Ultimate Home Office Setup Kit',
    description: 'Complete workspace enhancement: Lume Desk Lamp Pro + Quantum 360° Speaker + ClearView 4K AI Webcam.',
    tag: 'Save ₹2,700 (15% OFF)',
    products: [
      ASSISTANT_CATALOG[5], // Lume Lamp (₹4,499)
      ASSISTANT_CATALOG[4], // Quantum Speaker (₹7,999)
      ASSISTANT_CATALOG[7], // ClearView 4K Webcam (₹5,499)
    ],
    originalTotal: 17997,
    bundlePrice: 15297,
    savings: 2700,
    discountPercentage: 15,
    reason: 'Customers who bought these together reported a 40% improvement in call clarity and reduced eye fatigue.',
  },
  {
    id: 'bundle-power-commute',
    name: 'Everyday Commuter & Audio Pack',
    description: 'Bolt Sonic ANC Earbuds + Swift 65W GaN Power Bank + MagCharge 3-in-1 Stand.',
    tag: 'Save ₹1,500 (20% OFF)',
    products: [
      ASSISTANT_CATALOG[1], // Bolt Sonic (₹2,499)
      ASSISTANT_CATALOG[6], // Swift Power Bank (₹2,999)
      ASSISTANT_CATALOG[9], // MagCharge Stand (₹2,199)
    ],
    originalTotal: 7697,
    bundlePrice: 6197,
    savings: 1500,
    discountPercentage: 20,
    reason: 'Matches active mobile lifestyle. Keeps all your personal devices charged and gives you immersive ANC music on the go.',
  },
  {
    id: 'bundle-pro-productivity',
    name: 'Pro Creator & Developer Desk Set',
    description: 'Apex Pro Mechanical Keyboard + ErgoGrip Vertical Mouse + Lume Desk Lamp Pro.',
    tag: 'Save ₹1,800 (17% OFF)',
    products: [
      ASSISTANT_CATALOG[8], // Apex Keyboard (₹4,499)
      ASSISTANT_CATALOG[10], // Ergo Mouse (₹1,799)
      ASSISTANT_CATALOG[5], // Lume Lamp (₹4,499)
    ],
    originalTotal: 10797,
    bundlePrice: 8997,
    savings: 1800,
    discountPercentage: 17,
    reason: 'Engineered for comfort during 8+ hour work stretches with premium ergonomics and focused lighting.',
  },
];
