import { Prisma } from '@prisma/client'; import { prisma } from '../config/prisma.config.js'; import { AppError } from '../utils/app-error.js';
export const MAX_CART_QUANTITY=99;
export function cartSubtotal(lines:Array<{unitPrice:Prisma.Decimal;quantity:number}>):Prisma.Decimal { return lines.reduce((total,line)=>total.plus(line.unitPrice.mul(line.quantity)),new Prisma.Decimal(0)); }
function insufficient(available:number){ return new AppError({statusCode:409,code:'INSUFFICIENT_INVENTORY',message:`Only ${available} units are currently available.`}); }
export class CartService {
  private async active(storeId:string){ return prisma.shoppingCart.findFirst({where:{storeId,status:'ACTIVE'},orderBy:{updatedAt:'desc'},include:{items:{include:{product:{include:{inventory:true,productCategory:true}},variant:{include:{inventory:true}}}}}}); }
  private view(cart:any){ const items=cart.items.map((item:any)=>{const inventory=item.variant?.inventory?.[0]??item.product.inventory[0];const available=inventory?inventory.quantity-inventory.reservedQuantity:0; return {id:item.id,productId:item.productId,variantId:item.variantId,name:item.product.name,quantity:item.quantity,unitPrice:Number(item.unitPrice),currency:item.product.currency,subtotal:Number(item.unitPrice.mul(item.quantity)),availableQuantity:available};}); return {id:cart.id,items,subtotal:Number(cartSubtotal(cart.items)),currency:cart.currency,itemCount:items.reduce((n:any,i:any)=>n+i.quantity,0)}; }
  async get(storeId:string,actorId?:string){ const cart=await this.active(storeId); if(!cart) return {id:null,items:[],subtotal:0,currency:'INR',itemCount:0}; if(actorId) await prisma.analyticsEvent.create({data:{storeId,eventType:'CART_VIEWED',metadata:{cartId:cart.id}}}); return this.view(cart); }
  async add(storeId:string,actorId:string,input:{productId:string;variantId?:string;quantity:number}){ if(input.quantity<1||input.quantity>MAX_CART_QUANTITY) throw AppError.badRequest(`Quantity must be between 1 and ${MAX_CART_QUANTITY}`); const product=await prisma.product.findFirst({where:{id:input.productId,storeId},include:{variants:{include:{inventory:true}},inventory:true}}); if(!product) throw new AppError({statusCode:404,code:'PRODUCT_NOT_FOUND',message:'Product not found'}); if(product.status!=='ACTIVE'||!product.isActive) throw new AppError({statusCode:409,code:'PRODUCT_INACTIVE',message:'Product is not active'}); const variant=input.variantId?product.variants.find(v=>v.id===input.variantId):undefined; if(input.variantId&&!variant) throw new AppError({statusCode:422,code:'INVALID_VARIANT',message:'Variant does not belong to this product'}); if(product.variants.length&&!variant) throw new AppError({statusCode:422,code:'VARIANT_REQUIRED',message:'Select a product variant'}); const inventory=variant?.inventory[0]??product.inventory[0]; const available=inventory?inventory.quantity-inventory.reservedQuantity:0; const cart=await this.active(storeId); const existing=cart?.items.find((i:any)=>i.productId===product.id&&i.variantId===(variant?.id??null)); const quantity=(existing?.quantity??0)+input.quantity; if(available<quantity) throw insufficient(available); const saved=await prisma.$transaction(async tx=>{const target=cart??await tx.shoppingCart.create({data:{storeId,currency:product.currency}}); if(existing) await tx.cartItem.update({where:{id:existing.id},data:{quantity,unitPrice:variant?.price??product.price}}); else await tx.cartItem.create({data:{cartId:target.id,productId:product.id,variantId:variant?.id,quantity:input.quantity,unitPrice:variant?.price??product.price}}); await tx.auditEvent.create({data:{storeId,eventType:cart?'CART_ITEM_ADDED':'CART_CREATED',actorType:'USER',actorId,metadata:{cartId:target.id,productId:product.id,variantId:variant?.id,quantity}}}); await tx.analyticsEvent.create({data:{storeId,eventType:'PRODUCT_ADDED_TO_CART',productId:product.id,metadata:{cartId:target.id,quantity}}}); return target.id;}); return this.byId(storeId,saved); }
  async byId(storeId:string,id:string){const cart=await prisma.shoppingCart.findFirst({where:{id,storeId},include:{items:{include:{product:{include:{inventory:true,productCategory:true}},variant:{include:{inventory:true}}}}}});if(!cart)throw new AppError({statusCode:404,code:'CART_NOT_FOUND',message:'Cart not found'});return this.view(cart);}
  async update(storeId:string,actorId:string,itemId:string,quantity:number){if(quantity<1||quantity>MAX_CART_QUANTITY)throw AppError.badRequest(`Quantity must be between 1 and ${MAX_CART_QUANTITY}`);const cart=await this.active(storeId);const item=cart?.items.find((i:any)=>i.id===itemId);if(!cart||!item)throw new AppError({statusCode:404,code:'CART_NOT_FOUND',message:'Cart item not found'});const inventory=item.variant?.inventory?.[0]??item.product.inventory[0];const available=inventory?inventory.quantity-inventory.reservedQuantity:0;if(available<quantity)throw insufficient(available);await prisma.$transaction([prisma.cartItem.update({where:{id:itemId},data:{quantity,unitPrice:item.variant?.price??item.product.price}}),prisma.auditEvent.create({data:{storeId,eventType:'CART_ITEM_UPDATED',actorType:'USER',actorId,metadata:{cartId:cart.id,itemId,quantity}}}),prisma.analyticsEvent.create({data:{storeId,eventType:'CART_ITEM_UPDATED',metadata:{cartId:cart.id,itemId,quantity}}})]);return this.byId(storeId,cart.id);}
  async remove(storeId:string,actorId:string,itemId:string){const cart=await this.active(storeId);const item=cart?.items.find((i:any)=>i.id===itemId);if(!cart||!item)throw new AppError({statusCode:404,code:'CART_NOT_FOUND',message:'Cart item not found'});await prisma.$transaction([prisma.cartItem.delete({where:{id:itemId}}),prisma.auditEvent.create({data:{storeId,eventType:'CART_ITEM_REMOVED',actorType:'USER',actorId,metadata:{cartId:cart.id,itemId,productId:item.productId}}}),prisma.analyticsEvent.create({data:{storeId,eventType:'CART_ITEM_REMOVED',productId:item.productId,metadata:{cartId:cart.id}}})]);return this.byId(storeId,cart.id);}
  async clear(storeId:string,actorId:string){const cart=await this.active(storeId);if(!cart)return;await prisma.$transaction([prisma.cartItem.deleteMany({where:{cartId:cart.id}}),prisma.auditEvent.create({data:{storeId,eventType:'CART_CLEARED',actorType:'USER',actorId,metadata:{cartId:cart.id}}})]);}
}
export const cartService=new CartService();
