import { randomUUID } from 'node:crypto'; import { Prisma } from '@prisma/client'; import { prisma } from '../config/prisma.config.js'; import { AppError } from '../utils/app-error.js';
export class OrderService {
  async create(storeId:string,actorId:string,cartId:string){return prisma.$transaction(async tx=>{const cart=await tx.shoppingCart.findFirst({where:{id:cartId,storeId,status:'ACTIVE'},include:{items:true}});if(!cart)throw new AppError({statusCode:404,code:'CART_NOT_FOUND',message:'Cart not found'});if(!cart.items.length)throw new AppError({statusCode:409,code:'CART_EMPTY',message:'Cart is empty'});const items:any[]=[];let subtotal=new Prisma.Decimal(0);for(const line of cart.items){const product=await tx.product.findFirst({where:{id:line.productId,storeId,status:'ACTIVE',isActive:true},include:{variants:{include:{inventory:true}},inventory:true}});if(!product)throw new AppError({statusCode:409,code:'ORDER_VALIDATION_FAILED',message:'A cart product is no longer available'});const variant=line.variantId?product.variants.find(v=>v.id===line.variantId):undefined;if(line.variantId&&!variant)throw new AppError({statusCode:422,code:'INVALID_VARIANT',message:'A cart variant is no longer valid'});if(product.variants.length&&!variant)throw new AppError({statusCode:422,code:'VARIANT_REQUIRED',message:'A cart variant is no longer valid'});const inventory=variant?.inventory[0]??product.inventory[0];if(!inventory)throw new AppError({statusCode:409,code:'INSUFFICIENT_INVENTORY',message:'No inventory record is available for a cart item.'});const available=inventory.quantity-inventory.reservedQuantity;if(available<line.quantity)throw new AppError({statusCode:409,code:'INSUFFICIENT_INVENTORY',message:`Only ${available} units are currently available.`});const unitPrice=variant?.price??product.price;const totalPrice=unitPrice.mul(line.quantity);subtotal=subtotal.plus(totalPrice);items.push({product,variant,inventory,quantity:line.quantity,unitPrice,totalPrice});}
    const order=await tx.order.create({data:{storeId,orderNumber:`ORD-${Date.now()}-${randomUUID().slice(0,6)}`,status:'PENDING',paymentStatus:'PENDING',paymentMethod:'CASH_ON_DELIVERY',subtotal,total:subtotal,currency:cart.currency,items:{create:items.map(i=>({productId:i.product.id,variantId:i.variant?.id,productName:i.product.name,sku:i.variant?.sku??i.product.sku,quantity:i.quantity,unitPrice:i.unitPrice,totalPrice:i.totalPrice}))}},include:{items:true}});
    for(const item of items){const result=await tx.inventory.updateMany({where:{id:item.inventory.id,quantity:{gte:item.quantity+item.inventory.reservedQuantity}},data:{quantity:{decrement:item.quantity},reservedQuantity:{increment:item.quantity},status:item.inventory.quantity-item.quantity<=0?'OUT_OF_STOCK':'RESERVED'}});if(result.count!==1)throw new AppError({statusCode:409,code:'INSUFFICIENT_INVENTORY',message:'Inventory changed while creating the order.'});}
    await tx.shoppingCart.update({where:{id:cart.id},data:{status:'CHECKED_OUT'}});await tx.auditEvent.create({data:{storeId,orderId:order.id,eventType:'ORDER_CREATED',actorType:'USER',actorId,metadata:{cartId,orderNumber:order.orderNumber,total:subtotal.toString(),productIds:items.map(i=>i.product.id)}}});await tx.analyticsEvent.create({data:{storeId,orderId:order.id,eventType:'ORDER_CREATED',value:subtotal,currency:cart.currency,metadata:{cartId}}});return order;});}
  async list(storeId:string,page:number,limit:number,status?:any){const where:any={storeId,...(status?{status}:{})};const [orders,total]=await prisma.$transaction([prisma.order.findMany({where,include:{items:true},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}),prisma.order.count({where})]);return {orders,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
  async get(storeId:string,id:string){const order=await prisma.order.findFirst({where:{id,storeId},include:{items:true}});if(!order)throw new AppError({statusCode:404,code:'ORDER_NOT_FOUND',message:'Order not found'});return order;}
}
export const orderService=new OrderService();
