import type { DashboardSnapshot } from './types';

export const dashboardSnapshot: DashboardSnapshot = {
  merchantName: 'Acme Retail',
  kpis: [
    {
      key: 'revenue',
      label: "Today's Revenue",
      value: 284930,
      prefix: '₹ ',
      trend: 18.2,
      trendUp: true,
      icon: 'revenue',
      tone: 'from-brand-600/20 to-brand-500/10 text-brand-500 dark:text-brand-400 border-brand-500/20',
      glow: 'brand',
      sparkline: [
        { v: 32 }, { v: 45 }, { v: 38 }, { v: 52 }, { v: 48 }, { v: 61 }, { v: 70 },
        { v: 65 }, { v: 78 }, { v: 85 }, { v: 79 }, { v: 92 }, { v: 98 }, { v: 110 },
      ],
      chartType: 'area',
    },
    {
      key: 'orders',
      label: "Today's Orders",
      value: 342,
      trend: 24.6,
      trendUp: true,
      icon: 'orders',
      tone: 'from-ai-cyan/20 to-ai-cyan/10 text-ai-cyan border-ai-cyan/20',
      glow: 'cyan',
      sparkline: [
        { v: 18 }, { v: 22 }, { v: 28 }, { v: 25 }, { v: 34 }, { v: 40 }, { v: 38 },
        { v: 46 }, { v: 52 }, { v: 49 }, { v: 58 }, { v: 65 }, { v: 72 }, { v: 80 },
      ],
      chartType: 'bar',
    },
    {
      key: 'conversion',
      label: 'Conversion Rate',
      value: 4.82,
      suffix: '%',
      decimals: 2,
      trend: 5.4,
      trendUp: true,
      icon: 'conversion',
      tone: 'from-ai-emerald/20 to-ai-emerald/10 text-ai-emerald border-ai-emerald/20',
      glow: 'emerald',
      sparkline: [
        { v: 42 }, { v: 44 }, { v: 40 }, { v: 46 }, { v: 48 }, { v: 45 }, { v: 50 },
        { v: 52 }, { v: 51 }, { v: 55 }, { v: 58 }, { v: 56 }, { v: 60 }, { v: 62 },
      ],
      chartType: 'line',
    },
    {
      key: 'aov',
      label: 'Average Order Value',
      value: 8934,
      prefix: '₹ ',
      trend: 3.1,
      trendUp: true,
      icon: 'aov',
      tone: 'from-ai-violet/20 to-ai-violet/10 text-ai-violet border-ai-violet/20',
      glow: 'violet',
      sparkline: [
        { v: 70 }, { v: 72 }, { v: 68 }, { v: 74 }, { v: 78 }, { v: 76 }, { v: 82 },
        { v: 80 }, { v: 86 }, { v: 88 }, { v: 85 }, { v: 92 }, { v: 95 }, { v: 98 },
      ],
      chartType: 'area',
    },
    {
      key: 'ai-convos',
      label: 'Active AI Conversations',
      value: 128,
      trend: 42.3,
      trendUp: true,
      icon: 'conversations',
      tone: 'from-ai-violet/20 via-brand-500/15 to-ai-cyan/10 text-ai-violet border-ai-violet/25',
      glow: 'violet',
      sparkline: [
        { v: 20 }, { v: 28 }, { v: 34 }, { v: 30 }, { v: 42 }, { v: 48 }, { v: 56 },
        { v: 62 }, { v: 70 }, { v: 78 }, { v: 85 }, { v: 96 }, { v: 110 }, { v: 128 },
      ],
      chartType: 'area',
    },
    {
      key: 'growth',
      label: 'Revenue Growth',
      value: 24.8,
      suffix: '%',
      decimals: 1,
      trend: 8.6,
      trendUp: true,
      icon: 'growth',
      tone: 'from-ai-emerald/20 via-ai-cyan/15 to-brand-500/10 text-ai-emerald border-ai-emerald/25',
      glow: 'emerald',
      sparkline: [
        { v: 10 }, { v: 14 }, { v: 12 }, { v: 18 }, { v: 22 }, { v: 20 }, { v: 26 },
        { v: 30 }, { v: 28 }, { v: 34 }, { v: 38 }, { v: 36 }, { v: 42 }, { v: 45 },
      ],
      chartType: 'line',
    },
  ],
  revenue: [
    { day: 'Mon', revenue: 142000, ai: 88000, organic: 54000 },
    { day: 'Tue', revenue: 178000, ai: 112000, organic: 66000 },
    { day: 'Wed', revenue: 156000, ai: 96000, organic: 60000 },
    { day: 'Thu', revenue: 204000, ai: 138000, organic: 66000 },
    { day: 'Fri', revenue: 248000, ai: 172000, organic: 76000 },
    { day: 'Sat', revenue: 212000, ai: 146000, organic: 66000 },
    { day: 'Sun', revenue: 284930, ai: 196430, organic: 88500 },
  ],
  orders: [
    { day: 'Mon', paid: 128, pending: 22, refunded: 8 },
    { day: 'Tue', paid: 164, pending: 28, refunded: 12 },
    { day: 'Wed', paid: 142, pending: 24, refunded: 6 },
    { day: 'Thu', paid: 186, pending: 34, refunded: 14 },
    { day: 'Fri', paid: 228, pending: 42, refunded: 10 },
    { day: 'Sat', paid: 196, pending: 36, refunded: 18 },
    { day: 'Sun', paid: 284, pending: 48, refunded: 10 },
  ],
  funnel: [
    { step: 'Visitors', count: 18420, rate: 100, icon: 'visitors', tone: 'from-brand-600/30 to-brand-500/10 text-brand-500 border-brand-500/25', glow: 'rgba(99,102,241,0.35)' },
    { step: 'Viewed Product', count: 9860, rate: 53.5, icon: 'viewed', tone: 'from-ai-violet/30 to-ai-violet/10 text-ai-violet border-ai-violet/25', glow: 'rgba(139,92,246,0.35)' },
    { step: 'Searched / Filtered', count: 6240, rate: 33.9, icon: 'searched', tone: 'from-ai-cyan/30 to-ai-cyan/10 text-ai-cyan border-ai-cyan/25', glow: 'rgba(6,182,212,0.35)' },
    { step: 'Added to Cart', count: 2960, rate: 16.1, icon: 'cart', tone: 'from-ai-emerald/30 to-ai-emerald/10 text-ai-emerald border-ai-emerald/25', glow: 'rgba(16,185,129,0.35)' },
    { step: 'Checkout Started', count: 1810, rate: 9.8, icon: 'checkout', tone: 'from-amber-500/30 to-amber-500/10 text-amber-400 border-amber-500/25', glow: 'rgba(245,158,11,0.35)' },
    { step: 'Purchase', count: 888, rate: 4.82, icon: 'purchase', tone: 'from-emerald-500/30 to-emerald-500/10 text-emerald-400 border-emerald-500/25', glow: 'rgba(16,185,129,0.35)' },
  ],
  conversations: [
    { hr: '00', sessions: 42, conversions: 6, avgResp: 2.4 },
    { hr: '04', sessions: 28, conversions: 3, avgResp: 2.1 },
    { hr: '08', sessions: 86, conversions: 14, avgResp: 2.8 },
    { hr: '12', sessions: 148, conversions: 28, avgResp: 3.1 },
    { hr: '16', sessions: 172, conversions: 36, avgResp: 2.9 },
    { hr: '20', sessions: 126, conversions: 22, avgResp: 2.5 },
    { hr: 'Now', sessions: 98, conversions: 18, avgResp: 2.3 },
  ],
  conversationStats: [
    { label: 'Total Sessions', value: 1842, icon: 'sessions', tone: 'text-brand-500 bg-brand-500/10 border-brand-500/20' },
    { label: 'Products Shown', value: 12847, icon: 'shown', tone: 'text-ai-violet bg-ai-violet/10 border-ai-violet/20' },
    { label: 'Recommendations Accepted', value: 4821, icon: 'accepted', tone: 'text-ai-cyan bg-ai-cyan/10 border-ai-cyan/20' },
    { label: 'Orders Assisted', value: 384, icon: 'assisted', tone: 'text-ai-emerald bg-ai-emerald/10 border-ai-emerald/20' },
  ],
  topProducts: [
    { id: '1', name: 'Nexus Pro Wireless Earbuds', sku: 'NX-EAR-001', revenue: 684200, units: 284, views: 8420, conversion: 3.37, trend: 38, trendUp: true, aiBoosted: true, tone: 'from-brand-600/25 via-brand-500/15 to-transparent text-brand-500 border-brand-500/20' },
    { id: '2', name: 'Aura Smart Watch Ultra', sku: 'AU-WT-002', revenue: 528400, units: 128, views: 6180, conversion: 2.07, trend: 22, trendUp: true, aiBoosted: true, tone: 'from-ai-violet/25 via-ai-violet/15 to-transparent text-ai-violet border-ai-violet/20' },
    { id: '3', name: 'Bundle · Home Essentials Kit', sku: 'BD-HK-003', revenue: 412800, units: 164, views: 4860, conversion: 3.37, trend: 16, trendUp: true, aiBoosted: true, tone: 'from-ai-emerald/25 via-ai-emerald/15 to-transparent text-ai-emerald border-ai-emerald/20' },
    { id: '4', name: 'Quantum Bluetooth Speaker', sku: 'QT-SP-004', revenue: 284600, units: 96, views: 3840, conversion: 2.5, trend: 4, trendUp: false, aiBoosted: false, tone: 'from-ai-cyan/25 via-ai-cyan/15 to-transparent text-ai-cyan border-ai-cyan/20' },
    { id: '5', name: 'Lume Desk Lamp Pro', sku: 'LM-DL-005', revenue: 184200, units: 184, views: 2840, conversion: 6.48, trend: 12, trendUp: true, aiBoosted: false, tone: 'from-amber-500/25 via-amber-500/15 to-transparent text-amber-400 border-amber-500/20' },
  ],
  visitors: [
    { id: 'V-4821', location: 'Mumbai', country: 'India', flag: '🇮🇳', device: 'mobile', page: 'Wireless Earbuds PDP', activity: 'Viewing product', duration: '4m 12s', aiActive: true, tone: 'from-brand-600/25 to-brand-500/10 text-brand-500 border-brand-500/20', activityKind: 'view' },
    { id: 'V-4820', location: 'Bengaluru', country: 'India', flag: '🇮🇳', device: 'desktop', page: 'Bundle A · Home Kit', activity: 'AI recommending', duration: '2m 48s', aiActive: true, tone: 'from-ai-violet/25 to-ai-violet/10 text-ai-violet border-ai-violet/20', activityKind: 'ai' },
    { id: 'V-4819', location: 'Dubai', country: 'UAE', flag: '🇦🇪', device: 'mobile', page: 'Cart Review', activity: 'Added to cart', duration: '6m 32s', aiActive: false, tone: 'from-ai-emerald/25 to-ai-emerald/10 text-ai-emerald border-ai-emerald/20', activityKind: 'cart' },
    { id: 'V-4818', location: 'Singapore', country: 'SG', flag: '🇸🇬', device: 'desktop', page: 'Search: "smart watch"', activity: 'Searching', duration: '1m 08s', aiActive: true, tone: 'from-ai-cyan/25 to-ai-cyan/10 text-ai-cyan border-ai-cyan/20', activityKind: 'search' },
    { id: 'V-4817', location: 'London', country: 'UK', flag: '🇬🇧', device: 'mobile', page: 'Checkout · Step 2', activity: 'Payment info', duration: '8m 42s', aiActive: false, tone: 'from-amber-500/25 to-amber-500/10 text-amber-400 border-amber-500/20', activityKind: 'checkout' },
  ],
  insights: [
    { id: 'i1', title: 'Wireless Earbuds converting 38% better', detail: 'AI bundling + urgency messaging drove exceptional lift on Nexus Pro SKU.', impact: '+₹2.84L revenue', impactTone: 'positive', icon: 'bag', tone: 'from-brand-600/25 via-brand-500/15 to-transparent text-brand-500 border-brand-500/20', tag: 'Conversion' },
    { id: 'i2', title: 'Customers respond best to Bundle A', detail: 'Home Essentials Kit has 2.3× higher attachment rate than Bundle B.', impact: 'AOV +23.4%', impactTone: 'positive', icon: 'target', tone: 'from-ai-violet/25 via-ai-violet/15 to-transparent text-ai-violet border-ai-violet/20', tag: 'Bundling' },
    { id: 'i3', title: 'Cart abandonment reduced 21%', detail: 'AI nudges + timer checkouts recovered 184 extra carts this week.', impact: '+₹1.48L recovered', impactTone: 'positive', icon: 'cart', tone: 'from-ai-emerald/25 via-ai-emerald/15 to-transparent text-ai-emerald border-ai-emerald/20', tag: 'Recovery' },
  ],
  recommendations: [
    { id: 'r1', title: 'Launch "Buy 2, Get 15% Off" campaign', subtitle: 'On Aura Smart Watch + 2 accessories. Targets 4.2K cart abandoners.', kind: 'campaign', roi: 'Est. +₹4.8L / mo', effort: 'Low', icon: 'volume', tone: 'from-brand-600/25 via-brand-500/15 to-transparent text-brand-500 border-brand-500/20' },
    { id: 'r2', title: 'Add Free Shipping threshold at ₹2,499', subtitle: 'Lifts AOV by nudging users from ₹2,100 → ₹2,499 (+19%).', kind: 'pricing', roi: 'Est. +₹2.2L / mo', effort: 'Low', icon: 'gift', tone: 'from-ai-emerald/25 via-ai-emerald/15 to-transparent text-ai-emerald border-ai-emerald/20' },
    { id: 'r3', title: 'AI upsell: Speaker + Earbuds bundle', subtitle: '38% attachment rate on similar SKUs. Auto-apply at checkout.', kind: 'bundle', roi: 'Est. +₹3.1L / mo', effort: 'Medium', icon: 'bulb', tone: 'from-ai-violet/25 via-ai-violet/15 to-transparent text-ai-violet border-ai-violet/20' },
  ],
  campaigns: [
    { id: 'c1', name: 'Monsoon Flash · Earbuds', audience: 'Cart abandoners · 4.2K', channel: 'WhatsApp + Email', predictedLift: '+18% conv', status: 'ready' },
    { id: 'c2', name: 'Bundle A Highlight', audience: 'Repeat buyers · 1.8K', channel: 'On-site AI', predictedLift: '+23% AOV', status: 'ready' },
    { id: 'c3', name: 'Free Ship at ₹2,499', audience: 'Mid-cart · 6.1K', channel: 'Checkout nudge', predictedLift: '+11% AOV', status: 'draft' },
  ],
  alerts: [
    { id: 'a1', title: 'Inventory Low: Nexus Pro Earbuds', detail: 'Only 42 units left. Reorder point breached.', time: '8 min ago', level: 'warning' },
    { id: 'a2', title: 'AI Concierge Latency Spike', detail: 'US East region p95 3.8s → 6.2s. Monitoring.', time: '22 min ago', level: 'critical' },
    { id: 'a3', title: 'Upsell Campaign "Summer-24" Live', detail: 'Reaching 4,217 users across 3 segments.', time: '1 hr ago', level: 'success' },
    { id: 'a4', title: 'Razorpay Settlement Initiated', detail: '₹4,32,100 pending credit to A/C XXXX-8821.', time: '2 hr ago', level: 'info' },
  ],
  notifications: [
    { id: 'n1', title: 'Inventory Low: Nexus Pro Earbuds', detail: 'Only 42 units left. Reorder point breached.', time: '8 min ago', level: 'warning', unread: true },
    { id: 'n2', title: 'AI Concierge Latency Spike', detail: 'US East region p95 3.8s → 6.2s.', time: '22 min ago', level: 'critical', unread: true },
    { id: 'n3', title: 'New paid order · Priya Sharma', detail: 'Nexus Pro Wireless Earbuds · ₹12,490', time: '2 min ago', level: 'success', unread: true },
    { id: 'n4', title: 'Razorpay Settlement Initiated', detail: '₹4,32,100 pending credit.', time: '2 hr ago', level: 'info', unread: false },
  ],
  recentOrders: [
    { id: 'NX-20260829-001', customer: 'Priya Sharma', email: 'priya.s@example.com', product: 'Nexus Pro Wireless Earbuds × 1', amount: 12490, status: 'paid', payment: 'UPI', time: '2 min ago', aiAssisted: true },
    { id: 'NX-20260829-002', customer: 'Rahul Mehta', email: 'rahul.m@example.com', product: 'Home Essentials Bundle Kit × 1', amount: 24890, status: 'paid', payment: 'Card', time: '8 min ago', aiAssisted: true },
    { id: 'NX-20260829-003', customer: 'Anjali Verma', email: 'anjali.v@example.com', product: 'Aura Smart Watch Ultra × 1', amount: 18999, status: 'pending', payment: 'Net Banking', time: '14 min ago', aiAssisted: false },
    { id: 'NX-20260829-004', customer: 'Karthik Iyer', email: 'karthik.i@example.com', product: 'Quantum Bluetooth Speaker × 2', amount: 15798, status: 'paid', payment: 'UPI', time: '24 min ago', aiAssisted: true },
    { id: 'NX-20260829-005', customer: 'Sneha Reddy', email: 'sneha.r@example.com', product: 'Lume Desk Lamp Pro × 1', amount: 4499, status: 'refunded', payment: 'Razorpay Wallet', time: '38 min ago', aiAssisted: false },
    { id: 'NX-20260829-006', customer: 'Vikram Singh', email: 'vikram.s@example.com', product: 'Nexus Pro Wireless Earbuds × 1, Cable × 1', amount: 14248, status: 'paid', payment: 'Card', time: '52 min ago', aiAssisted: true },
    { id: 'NX-20260829-007', customer: 'Neha Kapoor', email: 'neha.k@example.com', product: 'Aura Smart Watch Ultra × 1', amount: 18999, status: 'pending', payment: 'UPI', time: '1 hr ago', aiAssisted: true },
  ],
  aiMetrics: [
    { label: 'Confidence Score', value: 92.4, suffix: '%', decimals: 1, target: 95, icon: 'confidence', tone: 'from-brand-600/30 via-brand-500/15 to-transparent text-brand-500 dark:text-brand-400 border-brand-500/25', description: 'AI recommendation quality against merchant goals', trend: { value: 3.8, up: true } },
    { label: 'Average Response Time', value: 2.4, suffix: 's', decimals: 1, target: 3, icon: 'latency', tone: 'from-ai-cyan/30 via-ai-cyan/15 to-transparent text-ai-cyan border-ai-cyan/25', description: 'Median time to first AI reply across channels', trend: { value: 12.6, up: true } },
    { label: 'Successful Recommendations', value: 4821, target: 5000, icon: 'recs', tone: 'from-ai-emerald/30 via-ai-emerald/15 to-transparent text-ai-emerald border-ai-emerald/25', description: 'Accepted product / bundle suggestions this week', trend: { value: 28.4, up: true } },
    { label: 'Checkout Success Rate', value: 78.6, suffix: '%', decimals: 1, target: 80, icon: 'checkout', tone: 'from-ai-violet/30 via-ai-violet/15 to-transparent text-ai-violet border-ai-violet/25', description: 'Users reaching checkout who completed payment', trend: { value: 6.2, up: true } },
    { label: 'Conversion Lift', value: 24.8, suffix: '%', decimals: 1, target: 30, icon: 'lift', tone: 'from-amber-500/30 via-amber-500/15 to-transparent text-amber-400 border-amber-500/25', description: 'Incremental conversion vs baseline (no AI)', trend: { value: 8.6, up: true } },
  ],
};
